wandb:
    use_wandb: true
    project: texas_vn
    entity: mls-stuttgart
    name: texas

ckpt: false

dataset: texas
data_path: ./datasets
batch_size: 1
lr: 1.e-3
weight_decay: 0.0005
debug: false
num_runs: 5
max_epoch: 1000
min_epoch: 100
patience: 100
scheduler_type: cos_with_warmup
scheduler_patience: 25
log_test: true

# encoder
encoder: null

#scorer_model: none
scorer_model:
    conv: gin
    hidden: 128
    num_conv_layers: 3
    num_mlp_layers: 2
    norm: graph_norm
    activation: gelu
    dropout: 0.
    num_centroids: 5

# extract the base nodes to super nodes
base2centroid:
    lazy_init: rand

# the hetero, hierarchical GNN
hetero:
    conv: gine
    hidden: 256
    cent_hidden: 384
    num_conv_layers: 3
    num_mlp_layers: 3
    norm: graph_norm
    activation: gelu
    dropout: 0.
    residual: true
    delay: 2
    aggr: mean
    parallel: false

sampler:
    name: simple
    sample_k: 1  # by default 1, i.e., each node gets assigned to 1 centroid
    num_ensemble: 2
    n_samples: 2
    assign_value: false  # use marginals to assign weights on the node masks

hybrid_model:
    jk: none
    target: base
    inter_pred_layer: 1
    intra_pred_layer: 1
    inter_ensemble_pool: mean
    intra_graph_pool: root