wandb:
    use_wandb: true
    project: baselines
    entity: mls-stuttgart
    name: wisconsin_gnn

ckpt: false

dataset: wisconsin
data_path: ./datasets
batch_size: 1
lr: 1.e-3
weight_decay: 0.
debug: false
num_runs: 5
max_epoch: 1000
min_epoch: 100
patience: 100
scheduler_type: cos_with_warmup
scheduler_patience: 25
log_test: true

# encoder
encoder: null

gnn:
    jk: none
    conv: gine
    hidden: 128
    num_conv_layers: 1
    norm: graph_norm
    activation: gelu
    dropout: 0.
    pred_layer: 2
    graph_pool: root