wandb:
    use_wandb: false
    project: debug
    entity: chendiqian
    name: run1_old

ckpt: false

dataset: hetero_cornell
data_path: ./datasets
batch_size: 1
lr: 1.e-3
weight_decay: 0.
debug: false
num_runs: 5
max_epoch: 1000
min_epoch: 100
patience: 100

# encoder
encoder: null

#scorer_model: none
scorer_model:
    conv: gin
    hidden: 64
    num_conv_layers: 0
    num_mlp_layers: 4
    norm: batch_norm
    activation: gelu
    dropout: 0.
    num_centroids: 5

# extract the base nodes to super nodes
base2centroid:
    conv: gine
    num_conv_layers: 2
    num_mlp_layers: 3
    norm: batch_norm
    activation: gelu
    dropout: 0.

# the hetero, hierarchical GNN
hetero:
    conv: gine
    hidden: 320
    num_conv_layers: 1
    num_mlp_layers: 2
    norm: batch_norm
    activation: gelu
    dropout: 0.
    residual: false
    aggr: mean
    parallel: false

sampler:
    name: simple
    sample_k: 1  # by default 1, i.e., each node gets assigned to 1 centroid
    num_ensemble: 1
    train_samples: 1
    val_samples: 1
    assign_value: true  # use marginals to assign weights on the node masks

hybrid_model:
    target: base
    inter_pred_layer: 1
    intra_pred_layer: 3
    inter_ensemble_pool: mean
    intra_graph_pool: root

#plots:
#    plot_every: 50
#    plot_folder: './plots'
#    mask: true
#    score: true

auxloss:
    scorer_label_supervised: 0.7
