wandb:
    use_wandb: true
    project: exp
    entity: chendiqian

ckpt: false

dataset: exp
data_path: ./datasets
batch_size: 64
lr: 1.e-3
weight_decay: 0.
debug: false
num_runs: 3
max_epoch: 1000
min_epoch: 300
patience: 100

# encoder
encoder:
    partition:
        dim_pe: 32

#scorer_model: none
scorer_model:
    conv: gin
    hidden: 64
    num_conv_layers: 0
    num_mlp_layers: 3
    norm: batch_norm
    activation: gelu
    dropout: 0.
    num_centroids: 5

# extract the base nodes to super nodes
base2centroid:
    conv: gine
    num_conv_layers: 4
    num_mlp_layers: 1
    norm: batch_norm
    activation: gelu
    dropout: 0.

# the hetero, hierarchical GNN
hetero:
    conv: gine
    hidden: 128
    num_conv_layers: 6
    num_mlp_layers: 2
    norm: batch_norm
    activation: gelu
    dropout: 0.5
    residual: false
    aggr: cat
    parallel: true

sampler:
    name: simple
    sample_k: 1  # by default 1, i.e., each node gets assigned to 1 centroid
    num_ensemble: 1
    train_samples: 1
    val_samples: 1
    assign_value: false  # use marginals to assign weights on the node masks

hybrid_model:
    target: base
    inter_pred_layer: 3
    intra_pred_layer: 2
    inter_ensemble_pool: mean
    intra_graph_pool: mean

auxloss:
    partition: 1.

plots:
    plot_every: 10
    plot_folder: './plots'
    score: true
    graph: true