program: sweep_run.py
method: bayes
entity: chendiqian
project: pep-func-first-sweep
run_cap: 50

metric:
  goal: maximize
  name: test_metric

parameters:
  ckpt:
    value: false

  dataset:
    value: peptides-func
  data_path:
    value: ./datasets
  batch_size:
    value: 64
  lr:
    value: 1.e-3
  weight_decay:
    value: 0.
  debug:
    value: false
  num_runs:
    value: 5
  max_epoch:
    value: 1000
  min_epoch:
    value: 100
  patience:
    value: 100

  encoder:
    parameters:
      atom:
        value: ogb
      bond:
        value: ogb

      rwse:
        parameters:
          kernel:
            value: 20
          layers:
            value: 2
          dim_pe:
            value: 32
          raw_norm_type:
            value: 'BatchNorm'

      lap:
        parameters:
          max_freqs:
            value: 4
          dim_pe:
            value: 32
          layers:
            value: 1
          raw_norm_type:
            value: none

  scorer_model:
    parameters:
      conv:
        value: gine
      hidden:
        values:
          - 128
          - 192
          - 256
          - 320
        distribution: categorical
      num_conv_layers:
        values:
          - 2
          - 3
          - 4
          - 5
        distribution: categorical
      num_mlp_layers:
        values:
          - 2
          - 3
          - 4
        distribution: categorical
      norm:
        values:
          - graph_norm
          - batch_norm
        distribution: categorical
      activation:
        value: gelu
      dropout:
        value: 0.
      num_centroids:
        value: 2

  base2centroid:
    parameters:
      conv:
        value: gine
      num_conv_layers:
        values:
          - 2
          - 3
          - 4
          - 5
        distribution: categorical
      num_mlp_layers:
        values:
          - 1
          - 2
          - 3
          - 4
        distribution: categorical
      norm:
        values:
          - batch_norm
          - graph_norm
        distribution: categorical
      activation:
        value: gelu
      dropout:
        value: 0.

  hetero:
    parameters:
      conv:
        value: gine
      hidden:
        values:
          - 128
          - 192
          - 256
          - 320
        distribution: categorical
      num_conv_layers:
        values:
          - 3
          - 4
          - 5
          - 6
        distribution: categorical
      num_mlp_layers:
        values:
          - 2
          - 3
          - 4
        distribution: categorical
      norm:
        values:
          - batch_norm
          - graph_norm
        distribution: categorical
      activation:
        value: gelu
      dropout:
        value: 0.
      residual:
        value: false
      aggr:
        value: cat
      parallel:
        value: true

  sampler:
    parameters:
      name:
        value: simple
      sample_k:
        value: 1
      num_ensemble:
        value: 1
      train_samples:
        value: 1
      val_samples:
        value: 1
      assign_value:
        value: false

  hybrid_model:
    parameters:
      target:
        value: base
      inter_pred_layer:
        values:
          - 1
          - 2
          - 3
          - 3
        distribution: categorical
      intra_pred_layer:
        values:
          - 1
          - 2
          - 3
          - 4
        distribution: categorical
      inter_ensemble_pool:
        value: mean
      intra_graph_pool:
        value: mean

#  auxloss:
#    parameters:
#      soft_empty:
#        values:
#          - 0.
#          - 1.e-5
#          - 1.e-4
#          - 1.e-3
#        distribution: categorical
#      hard_empty:
#        values:
#          - 0.
#          - 1.e-5
#          - 1.e-4
#          - 1.e-3
#        distribution: categorical

  plots:
    parameters:
      plot_every:
        value: 20
      mask:
        value: true
      score:
        value: true