wandb:
    use_wandb: false
    project: zinc
    entity: chendiqian
#    name: run1

ckpt: false

dataset: zinc
data_path: ./datasets
batch_size: 128
lr: 1.e-3
weight_decay: 0.
debug: false
num_runs: 3
max_epoch: 1000
min_epoch: 300
patience: 100

# encoder
encoder:
    rwse:
        kernel: 20
        layers: 2
        dim_pe: 32
        raw_norm_type: 'BatchNorm'

    lap:
        max_freqs: 4
        dim_pe: 32
        layers: 1
        raw_norm_type: null

gnn:
    jk: none
    conv: gine
    hidden: 192
    num_conv_layers: 5
    norm: batch_norm
    activation: gelu
    dropout: 0.

    pred_layer: 2
    graph_pool: mean
